---
title: "preface"
author: "Chang et. al."
date: "11/16/2024"
output: html_document
---




To facilitate a more comprehensive understanding of our revolutionary engine, we present to your distinguished company the culmination of this innovation -- the Dynamite Engine, based on our pattern: Patent No. US 11697993.

Traditional internal combustion engines capitalize on the explosive energy of petrochemical fuels to drive propulsion. In contrast, our new design can harness dynamites/more volatile compounds like Ammonium Nitrate (NH4NO3). This distinction originates from:

1.  Traditional engines employ rather slender crankshafts that cannot bear the impact of large explosive forces. In contrast, our new engine uses a thick and robust shaft, more than capable of withstanding high explosive impacts.

2.  In conventional engines, the explosion occurs precisely when the piston, connecting rod, and crankshaft align in a straight line. This confined explosive energy can make the engine unsustainable when using high-explosive materials, even risking an engine explosion. However, in the new engine, the explosion point coincides with the piston's movement downward on an inclined plane. The explosive force from the material can be channeled without any obstruction, propelling the rotor, hence preventing an engine explosion.

The successful realization of the Dynamite Engine represents a groundbreaking stride in humanity's ability to harness the raw power of explosives, effectively converting chemical energy into mechanical energy. This achievement promises more than simply diminishing our reliance on crude oil; it presents an opportunity to significantly mitigate environmental issues, such as air pollution and CO2-induced global warming.

Whether utilizing petroleum-based fuels or explosive compounds, the Kuei-Yin Rotary Engine's versatility promises to usher in a new industrial era. The potential applications extend beyond its military uses and could spark a major industrial revolution, including:

1.  Serving as a high-efficiency power source for industrial power generation.

2.  Providing an economical propulsion system for high-speed railways, eliminating the need for expensive electrical transmission systems, and substantially reducing construction costs.

3.  Enhancing marine navigation by improving the speed of sea vessels.

We earnestly hope that your company will recognize the transformative potential of our engine and champion its research and development. We believe that such an endeavor promises immense benefits for your organization, the strength of the nation, and the overall welfare of humanity. Please contact [changetalia@gmail.com](mailto:changetalia@gmail.com) for further information, should you be interested in participating this opportunity.

